---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: alerts
  namespace: {{ .Release.Namespace }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"