---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/sushan/Documents/data/grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.persistence.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi