---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}-headless
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
