apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-beyla-config
  namespace: monitoring
data:
  beyla.alloy: |
    beyla.ebpf "integrations_beyla" {
      attributes {
        kubernetes {
          enable = "true"
        }
      }

      discovery {
        services {
          kubernetes {
            namespace = ".*"
          }
        }
      }

      metrics {
        features = ["application"]
      }

      output {
        traces = [otelcol.exporter.otlp.tempo.input]
      }
    }

    discovery.relabel "integrations_beyla" {
      targets = beyla.ebpf.integrations_beyla.targets

      rule {
        target_label = "instance"
        replacement  = constants.hostname
      }

      rule {
        target_label = "job"
        replacement  = "integrations/beyla"
      }
    }

    prometheus.scrape "integrations_beyla" {
      scrape_interval = "15s"
      targets         = discovery.relabel.integrations_beyla.output
      honor_labels    = true
      forward_to      = [prometheus.remote_write.default.receiver]
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo:4317"
        tls {
          insecure = true
        }
      }
    }