apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.targetPort }}
    - port: {{ .Values.service.loki_port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.loki_name }}
      targetPort: {{ .Values.service.loki_targetPort }}
  selector:
    name: grafana-alloy