# values-staging.yaml
replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi

persistence:
  size: 20Gi

config:
  compactor:
    compaction:
      blockRetention: 72h
  querier:
    maxConcurrentQueries: 30